//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fuca
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public int id { get; set; }
        public string user_namee { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string addresss { get; set; }
        public Nullable<System.DateTime> datee { get; set; }
        public string department { get; set; }
    }
}
