//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fuca
{
    using System;
    using System.Collections.Generic;
    
    public partial class userss
    {
        public string user_namee { get; set; }
        public Nullable<int> passwordd { get; set; }
    }
}
